apiVersion: apps/v1
kind: Deployment
metadata:
  name: japanese-flash-card
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: japanese-flash-card
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
