apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: japanese-flash-card-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/236sec/japanese-flash-card-manifests.git
    path: overlays/dev
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: japanese-flash-card-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/236sec/japanese-flash-card-manifests.git
    path: overlays/prod
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    # Prod should be manual — you decide when to sync
    automated: {}
    syncOptions:
      - CreateNamespace=true
