apiVersion: apps/v1
kind: Deployment
metadata:
  name: japanese-flash-card
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: japanese-flash-card
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
